version: '3'
services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/get"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
